apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF6TURZeApPVFUwTkRaYUZ3MDBNekF6TURZeE9UVTBORFphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEbXZnM2RwZXR2VVBPOVUxRjhiUWdHSEd4Qjk0ZWpDeDZPWWZ0ZWdFdUZDeGxvdmE2OApBZEZkdWdodWV3QkJEVGFFYklXUElWZG9zc1lUVmZUZm52Tld5bDVKUVNTTjllQ3hKZG5FTWpJMEtsZHZYTThXCkk4ekp4SjgvN3RZVjBjay9GWHkrdFROL2lzYkk4bW5IRWcxalFGNXBuclpaOFE2c2d2a3FjZ25CMzh6WW4vYVIKWTJ2b1pTTDJ1RUFFYmpmT3ptdmZkT2QybWZ0RndpSUZpbWFwbUVobkhZbnFHUXZrUmI0NnpjOC9vbllzaWVQTgpYVzJ6WElVVTJzcUNOTWJYSW9GUGIydllpanlRZ0U2d2NvNUpzem9pV1FNMnpqUForVjE4dU5EZ1dpMTRtR1JvCmtqWkN1MisvTXZVbW92Y1doQW9lYmMzU0RUazZDeG9CY3FHdEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlE4TVAwV0cyV2s1SjY2RjZwMgpTbEZJV1pWYzNqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsNFVHVFFnbWhFcXRKaXZSQUJYaDF0cmQ5aHpVCmdIT3MxS0ZhLzdXRVVrTWVKOThsZjY3UVoyYnlFc2xyZmlHelh3S2lyUkxDQXpacDJqaEFoSm9uWEUwTENDdzkKWkJoU0ZGNER2WC9yUVRHYUN1aHR0WWFCOWsxZ1NSYVZNMzl0QyttRXN4cTBOcU5RLzIxdlNUaGRnNk1CeVkzQwpmNUpNeEhtNnFLaXJxK3M5VkRZYzdhbndabDNoVGE0OGNJMHArNy94RlNzRmF6TGZpajNXQ3NvWFZTT1MvNmYxCk5MaVpNTkxONmVDOFFEMW1CdUE2LzZWU1FUVGpVM0hjS0VYL04rT3FVcUVzb1NUWGRjQXhhZFdWYVRFd2lzVTcKM2FVenhNUVgwMm4wMWsrcURMMXdyKzVhR3RjV2ViVEFoNmlqbnNDSDRjZ2lMQ0ZQcXJ5OGRYRCsydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://66c913da-6792-4457-89cc-338e1cb81e6e.k8s.ondigitalocean.com
  name: do-blr1-django-k8
contexts:
- context:
    cluster: do-blr1-django-k8
    user: do-blr1-django-k8-admin
  name: do-blr1-django-k8
current-context: do-blr1-django-k8
kind: Config
preferences: {}
users:
- name: do-blr1-django-k8-admin
  user:
    token: dop_v1_5d07c874ae0bf5e5818894f00cab884621d45de83cbd24b65fe76411ff07a8b8
